%YAML:1.0
---
min_ratio: 0.03
max_ratio: 0.4
max_angle_l: 40.0
min_light_ratio: 0.7
min_small_center_distance: 0.8
max_small_center_distance: 3.2
min_large_center_distance: 3.2
max_large_center_distance: 5.5
max_angle_a: 50.0
threshold: 0.7